USE [ECOMMERCE]
GO

CREATE TABLE TB_USUARIOS (
    USUARIO_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(255) NOT NULL,
	EMAIL NVARCHAR(255) NOT NULL
);

CREATE TABLE TB_CATEGORIAS (
	CATEGORIA_ID INT NOT NULL PRIMARY KEY,
	ATIVO BIT NOT NULL,
	USUARIO_INSERCAO_ID INT NOT NULL,
	DATA_INSERCAO DATETIME NOT NULL,
	USUARIO_ATUALIZACAO_ID INT NULL,
	DATA_ATUALIZACAO DATETIME NULL,
    DESCRICAO NVARCHAR(255) NOT NULL,
    PORCENTAGEM_DESCONTO NUMERIC(15,2) NOT NULL,
	CONSTRAINT FK_USUARIO_INSERCAO_CATEGORIA FOREIGN KEY (USUARIO_INSERCAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_USUARIO_ATUALIZACAO_CATEGORIA FOREIGN KEY (USUARIO_ATUALIZACAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID)
);

CREATE TABLE TB_CLIENTES (
    CLIENTE_ID NVARCHAR(100) NOT NULL PRIMARY KEY,
	ATIVO BIT NOT NULL,
	USUARIO_INSERCAO_ID INT NOT NULL,
	DATA_INSERCAO DATETIME NOT NULL,
	USUARIO_ATUALIZACAO_ID INT NULL,
	DATA_ATUALIZACAO DATETIME NULL,
    NOME NVARCHAR(255) NOT NULL,
    CPF NVARCHAR(20) NOT NULL,
    CATEGORIA_ID INT,
	CONSTRAINT FK_USUARIO_INSERCAO_CLIENTE FOREIGN KEY (USUARIO_INSERCAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_USUARIO_ATUALIZACAO_CLIENTE FOREIGN KEY (USUARIO_ATUALIZACAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_TIPO_CLIENTE_CLIENTE FOREIGN KEY (CATEGORIA_ID)
    REFERENCES TB_CATEGORIAS(CATEGORIA_ID)
);

CREATE TABLE TB_PRODUTOS (
    PRODUTO_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ATIVO BIT NOT NULL,
	USUARIO_INSERCAO_ID INT NOT NULL,
	DATA_INSERCAO DATETIME NOT NULL,
	USUARIO_ATUALIZACAO_ID INT NULL,
	DATA_ATUALIZACAO DATETIME NULL,
    DESCRICAO NVARCHAR(255) NOT NULL,
    PRECO_UNITARIO NUMERIC(15,2) NOT NULL,
	CONSTRAINT FK_USUARIO_INSERCAO_PRODUTO FOREIGN KEY (USUARIO_INSERCAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_USUARIO_ATUALIZACAO_PRODUTO FOREIGN KEY (USUARIO_ATUALIZACAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID)
);

CREATE TABLE TB_STATUS_PEDIDOS (
    STATUS_PEDIDO_ID INT NOT NULL PRIMARY KEY,
	ATIVO BIT NOT NULL,
	USUARIO_INSERCAO_ID INT NOT NULL,
	DATA_INSERCAO DATETIME NOT NULL,
	USUARIO_ATUALIZACAO_ID INT NULL,
	DATA_ATUALIZACAO DATETIME NULL,
	DESCRICAO NVARCHAR(255) NULL,
	CONSTRAINT FK_USUARIO_INSERCAO_STATUS_PEDIDO FOREIGN KEY (USUARIO_INSERCAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_USUARIO_ATUALIZACAO_STATUS_PEDIDO FOREIGN KEY (USUARIO_ATUALIZACAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID)
);

CREATE TABLE TB_PEDIDOS (
    PEDIDO_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	USUARIO_INSERCAO_ID INT NOT NULL,
	DATA_INSERCAO DATETIME NOT NULL,
	USUARIO_ATUALIZACAO_ID INT NULL,
	DATA_ATUALIZACAO DATETIME NULL,
    DATA_VENDA DATETIME NOT NULL DEFAULT GETDATE(),
	CLIENTE_ID NVARCHAR(100) NOT NULL,
    STATUS_PEDIDO_ID INT NOT NULL,
	CONSTRAINT FK_USUARIO_INSERCAO_PEDIDO FOREIGN KEY (USUARIO_INSERCAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_USUARIO_ATUALIZACAO_PEDIDO FOREIGN KEY (USUARIO_ATUALIZACAO_ID)
    REFERENCES TB_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_CLIENTE_PEDIDO FOREIGN KEY (CLIENTE_ID)
    REFERENCES TB_CLIENTES(CLIENTE_ID),
	CONSTRAINT FK_STATUS_PEDIDO_PEDIDO FOREIGN KEY (STATUS_PEDIDO_ID)
    REFERENCES TB_STATUS_PEDIDOS(STATUS_PEDIDO_ID)
);

CREATE TABLE TB_ITENS_PEDIDO (
    ITEM_PEDIDO_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    PEDIDO_ID INT NOT NULL,
    PRODUTO_ID INT NOT NULL,
	DESCRICAO NVARCHAR(255) NULL,
    QUANTIDADE INT NOT NULL,
	PRECO_UNITARIO NUMERIC(15,2) NULL,
	CONSTRAINT FK_PEDIDO_ITEM_PEDIDO FOREIGN KEY (PEDIDO_ID)
    REFERENCES TB_PEDIDOS(PEDIDO_ID),
	CONSTRAINT FK_PRODUTO_ITEM_PEDIDO FOREIGN KEY (PRODUTO_ID)
    REFERENCES TB_PRODUTOS(PRODUTO_ID)
);

CREATE TABLE TB_FATURAMENTOS (
    FATURAMENTO_ID INT PRIMARY KEY IDENTITY(1,1),
    PEDIDO_ID INT NOT NULL,
    SUB_TOTAL NUMERIC(15,2) NOT NULL,
	DESCONTOS NUMERIC(15,2) NULL,
	VALOR_TOTAL NUMERIC(15,2) NOT NULL,
    CONSTRAINT FK_PEDIDO_FATURAMENTO FOREIGN KEY (PEDIDO_ID)
    REFERENCES TB_PEDIDOS(PEDIDO_ID)
);